page_title                                : Wonderple

ios_app_id                                :
ios_app_country                           :
appstore_link                             :
playstore_link                            : https://play.google.com/store/apps/details?id=com.meolly.fridge
presskit_download_link                    :

shortcut_icon                             : assets/shortcut.png
company_icon                              : 
company_name                              : Wonderple

app_icon                                  : assets/appicon.png
app_name                                  : Wonder Fridge
app_price                                 :
app_description                           : Wonderful, Easy Groceries Organizer

features                                  :
  - title                                 : 개인 냉장고
    title_eng                             : Personal fridge
    description                           : 로그인 없이도 간편하게 냉장고를 관리할 수 있어요.
    description_eng                       : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    fontawesome_icon_name                 : user
    
  - title                                 : 패밀리 냉장고
    title_eng                             : Family fridge
    description                           : 가족과 함께 냉장고를 관리할 수 있어요.
    description_eng                       : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : users

  - title                                 : 식품 데이터
    title_eng                             : Food data
    description                           : 미리 정의된 다양한 식품을 이용해 쉽고 편리하게 보관 중인 식품을 등록할 수 있어요.
    description_eng                       : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : book

  - title                                 : 간단한 입력 절차
    title_eng                             : Easy to add
    description                           : 냉장실, 냉동실, 실온으로 나누어진 보관장소에 쉽게 추가해 보세요!
    description_eng                       : Adding food items has never been this effortless.
    fontawesome_icon_name                 : plus

  - title                                 : 소비기한 알림
    title_eng                             : Notify exp. dates
    description                           : 입력된 소비기한을 바탕으로 원하는 날짜/시간에 알림을 보내드려요.
    description_eng                       : Enter your food expiration dates and receive notifications at your preferred times.
    fontawesome_icon_name                 : bell
  
  - title                                 : 장보기 목록
    title_eng                             : Shopping list
    description                           : 구매할 식품을 장보기 목록으로 간편하게 관리하세요.
    description_eng                       : Easily manage the food items you need to purchase with a shopping list.
    fontawesome_icon_name                 : shopping-basket

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.


topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"
cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8
device_color                              : black
body_background_color                     : "#ffffff"
link_color                                : "#346ed6"
app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"
feature_title_color                       : "#000000"
feature_text_color                        : "#666666"
feature_icons_foreground_color            : "#346ed6"
feature_icons_background_color            : "#e6e6e6"
social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"
footer_text_color                         : "#666666"

sass:
  style: :compressed

exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

markdown: kramdown