page_title                                : Wonderple

ios_app_id                                :
ios_app_country                           :
appstore_link                             :
playstore_link                            : https://play.google.com/store/apps/details?id=com.meolly.fridge
presskit_download_link                    :

shortcut_icon                             : assets/shortcut.png
company_icon                              : 
company_name                              : Wonderple

app_icon                                  : assets/appicon.png
app_name                                  : Wonder Fridge
app_price                                 :
app_description                           : Wonderful, Easy Groceries Organizer


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Personal fridge
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
    fontawesome_icon_name                 : user
    
  - title                                 : Family fridge
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : users

  - title                                 : Food items
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : cutlery

  - title                                 : Easy to add
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name                 : plus

  - title                                 : Notify
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : bell
  
  - title                                 : Shopping list
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : shopping-basket

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#346ed6"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#346ed6"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


languages: ["en", "it", "de", "fr", "ko"]
default_lang: "en"
exclude_from_localization: ["_pages", "_sass"]
parallel_localization: false

# data
hello:
  en: Hello!
  it: Ciao!
  de: Hallo!
  fr: Bonjour!
  ko: 안녕하세요!


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
